create database fop;

/*Users table*/
create table users
(
    id          int generated always as identity primary key,
    role        role_catalog_enum not null,
    name        varchar           not null,
    user_name   varchar unique    not null,
    password    varchar           not null,
    birth_date  date              not null,
    email       varchar unique    not null,
    is_active   bool                     default true,
    last_login  timestamp with time zone,
    created_at  timestamp with time zone default now(),
    uploaded_at timestamp with time zone default now()
);


create table investigators_profile
(
    investigator_id int primary key references users (id) on delete cascade,
    badge_number    varchar unique not null,
    created_at      timestamp with time zone default now(),
    uploaded_at     timestamp with time zone default now()
);

create table doctors_profile
(
    doctor_id      int primary key references users (id) on delete cascade,
    badge_number   varchar unique not null,
    specialization varchar        not null,
    created_at     timestamp with time zone default now(),
    uploaded_at    timestamp with time zone default now()
);


/*Enums for sex and death type*/
create type role_catalog_enum as enum ('sudo', 'doctor', 'investigator');
create type sex_catalog_enum as enum ('male', 'female', 'Undetermined');
create type death_catalog_enum as enum ('homicide', 'suicide', 'accident', 'natural', 'undetermined', 'pending investigation');


/*Tables for sex and death type catalog*/
create table sex_catalog
(
    sex_id      int generated always as identity primary key,
    type        sex_catalog_enum unique not null,
    created_at  timestamp with time zone default now(),
    uploaded_at timestamp with time zone default now()
);

create table death_catalog
(
    death_catalog_id int generated always as identity primary key,
    type             death_catalog_enum unique not null,
    created_at       timestamp with time zone default now(),
    uploaded_at      timestamp with time zone default now()
);


/*Cases and autopsy*/
create table cases
(
    case_id         int generated by default as identity primary key,
    case_date       timestamp with time zone default now(),
    location        varchar                                                                  not null,
    description     varchar                                                                  not null,
    type_death_id   int references death_catalog (death_catalog_id)                          not null,
    investigator_id int references investigators_profile (investigator_id) on delete cascade not null,
    created_at      timestamp with time zone default now(),
    uploaded_at     timestamp with time zone default now()
);

create table autopsy
(
    autopsy_id      int generated by default as identity primary key,
    autopsy_date    timestamp with time zone default now(),
    case_origin_id  int references cases (case_id)                               not null,
    doctor_id       int references doctors_profile (doctor_id) on delete cascade not null,
    description     varchar                                                      not null,
    type_death_id   int references death_catalog (death_catalog_id)              not null,
    current_version int                                                          not null,
    created_at      timestamp with time zone default now(),
    uploaded_at     timestamp with time zone default now()
);

create table autopsy_history
(
    autopsy_history_id int generated by default as identity primary key,
    autopsy_id         int references autopsy (autopsy_id) on delete cascade        not null,
    version_number     int                                                          not null,
    autopsy_date       timestamp with time zone default now(),
    doctor_id          int references doctors_profile (doctor_id) on delete cascade not null,
    description        varchar                                                      not null,
    type_death_id      int references death_catalog (death_catalog_id)              not null,
    change_reason      varchar                                                      not null,
    modified_at        timestamp with time zone default now()
);

create table victim_record
(
    victim_record_id      int generated always as identity primary key,
    case_id               int references cases (case_id) on delete cascade      not null,
    autopsy_id            int references autopsy (autopsy_id) on delete cascade not null,
    victim_name           varchar                                               not null,
    victim_death_date     timestamp with time zone default now(),
    victim_age            int check ( victim_age between 0 and 130)             not null,
    victim_identity_badge int                                                   not null,
    victim_sex            int references sex_catalog (sex_id)                   not null
);

